"""add revocation tracking to api keys

Revision ID: 01cca2803a26
Revises: d7b9bb6e23a7
Create Date: 2026-07-17 17:18:14.655473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cca2803a26'
down_revision: Union[str, Sequence[str], None] = 'd7b9bb6e23a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('api_keys', sa.Column('revoked_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'revoked_by')
    op.drop_column('api_keys', 'revoked_at')
    # ### end Alembic commands ###
