"""made payment provider field nullable in projects

Revision ID: 0a30fe28c3c0
Revises: 0aae136adcfe
Create Date: 2026-07-31 12:15:24.818570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a30fe28c3c0'
down_revision: Union[str, Sequence[str], None] = '0aae136adcfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'payment_provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'payment_provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
