"""added payment provider field to projects model

Revision ID: 0aae136adcfe
Revises: 9803670ae6f8
Create Date: 2026-07-31 12:12:55.115243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aae136adcfe'
down_revision: Union[str, Sequence[str], None] = '9803670ae6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('payment_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'payment_provider')
    # ### end Alembic commands ###
