"""adding foreign key event_type_id to invoice item model

Revision ID: 133c28e9ffb4
Revises: ca3f84a37519
Create Date: 2026-07-21 16:43:55.130578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133c28e9ffb4'
down_revision: Union[str, Sequence[str], None] = 'ca3f84a37519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('event_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoice_items', 'event_types', ['event_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_column('invoice_items', 'event_type_id')
    # ### end Alembic commands ###
