"""making important fields in user model not nullable

Revision ID: 14d56fcfb2b4
Revises: a89511f9daf0
Create Date: 2026-08-08 13:41:25.209553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14d56fcfb2b4'
down_revision: Union[str, Sequence[str], None] = 'a89511f9daf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'next_billing_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'default_currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'default_currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'next_billing_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
