"""making ext_id field in invoices not nullable

Revision ID: 1b1aa043d57e
Revises: 3602b1b53b11
Create Date: 2026-07-25 11:07:43.219232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1aa043d57e'
down_revision: Union[str, Sequence[str], None] = '3602b1b53b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
