"""making client external_id and project external_id not nullable

Revision ID: 1e477271fd3c
Revises: 5274ed041e99
Create Date: 2026-07-26 11:47:04.170390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e477271fd3c'
down_revision: Union[str, Sequence[str], None] = '5274ed041e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
