"""made external_id in apikeys model and idempotency_key in usage events not nullable

Revision ID: 23467dbaaf5c
Revises: 5cc80942a53b
Create Date: 2026-07-20 15:14:57.277120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23467dbaaf5c'
down_revision: Union[str, Sequence[str], None] = '5cc80942a53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usage_events', 'idempotency_key',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_events', 'idempotency_key',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('api_keys', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
