"""adding unique constraint for project_id and event_type in pricing_rules model

Revision ID: 24203db206f2
Revises: 113dcf1bbe6e
Create Date: 2026-03-29 13:57:56.471869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24203db206f2'
down_revision: Union[str, Sequence[str], None] = '113dcf1bbe6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_project_event', 'pricing_rules', ['project_id', 'event_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_project_event', 'pricing_rules', type_='unique')
    # ### end Alembic commands ###
