"""adding external_id field to invoices

Revision ID: 3602b1b53b11
Revises: c793e84e4753
Create Date: 2026-07-25 11:01:33.855371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3602b1b53b11'
down_revision: Union[str, Sequence[str], None] = 'c793e84e4753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('external_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'invoices', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_column('invoices', 'external_id')
    # ### end Alembic commands ###
