"""added external_id column to models event_type and pricing_rule

Revision ID: 49293e5ad4f9
Revises: 91aab7841bee
Create Date: 2026-08-18 10:44:39.180041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49293e5ad4f9'
down_revision: Union[str, Sequence[str], None] = '91aab7841bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('external_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'event_types', ['external_id'])
    op.add_column('pricing_rules', sa.Column('external_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'pricing_rules', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pricing_rules', type_='unique')
    op.drop_column('pricing_rules', 'external_id')
    op.drop_constraint(None, 'event_types', type_='unique')
    op.drop_column('event_types', 'external_id')
    # ### end Alembic commands ###
