"""adding external_id field to projects

Revision ID: 5274ed041e99
Revises: 1b1aa043d57e
Create Date: 2026-07-26 11:36:17.550068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5274ed041e99'
down_revision: Union[str, Sequence[str], None] = '1b1aa043d57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('external_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'projects', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'external_id')
    # ### end Alembic commands ###
