"""adding idempotency_key field to usageEvents

Revision ID: 5cc80942a53b
Revises: 71979aade062
Create Date: 2026-07-20 14:49:39.136056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc80942a53b'
down_revision: Union[str, Sequence[str], None] = '71979aade062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_events', sa.Column('idempotency_key', sa.String(length=36), nullable=True))
    op.create_index('ix_client_idempotency', 'usage_events', ['client_id', 'idempotency_key'], unique=False)
    op.create_unique_constraint('uq_client_idempotency', 'usage_events', ['client_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_idempotency', 'usage_events', type_='unique')
    op.drop_index('ix_client_idempotency', table_name='usage_events')
    op.drop_column('usage_events', 'idempotency_key')
    # ### end Alembic commands ###
