"""adjusting pricing rule and usage events model for event_type

Revision ID: 5f41ce46002f
Revises: 25e9fcb63ad7
Create Date: 2026-07-21 12:27:49.628850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f41ce46002f'
down_revision: Union[str, Sequence[str], None] = '25e9fcb63ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_rules', sa.Column('event_type_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uix_project_event'), 'pricing_rules', type_='unique')
    op.drop_constraint(op.f('pricing_rules_project_id_fkey'), 'pricing_rules', type_='foreignkey')
    op.create_foreign_key(None, 'pricing_rules', 'event_types', ['event_type_id'], ['id'])
    op.drop_column('pricing_rules', 'project_id')
    op.drop_column('pricing_rules', 'event_type')
    op.add_column('usage_events', sa.Column('event_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usage_events', 'event_types', ['event_type_id'], ['id'])
    op.drop_column('usage_events', 'event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_events', sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usage_events', type_='foreignkey')
    op.drop_column('usage_events', 'event_type_id')
    op.add_column('pricing_rules', sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pricing_rules', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pricing_rules', type_='foreignkey')
    op.create_foreign_key(op.f('pricing_rules_project_id_fkey'), 'pricing_rules', 'projects', ['project_id'], ['id'])
    op.create_unique_constraint(op.f('uix_project_event'), 'pricing_rules', ['project_id', 'event_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('pricing_rules', 'event_type_id')
    # ### end Alembic commands ###
