"""makingpricing_rule and event_type have one to one relationship and making event_type_id not nullable in usage_events

Revision ID: 675128f867ac
Revises: 5f41ce46002f
Create Date: 2026-07-21 12:57:08.518664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675128f867ac'
down_revision: Union[str, Sequence[str], None] = '5f41ce46002f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pricing_rules', ['event_type_id'])
    op.alter_column('usage_events', 'event_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_events', 'event_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'pricing_rules', type_='unique')
    # ### end Alembic commands ###
