"""add ext_id for apiKey model

Revision ID: 71979aade062
Revises: 01cca2803a26
Create Date: 2026-07-18 11:06:41.572465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71979aade062'
down_revision: Union[str, Sequence[str], None] = '01cca2803a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_api_keys_external_id'), 'api_keys', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_external_id'), table_name='api_keys')
    op.drop_column('api_keys', 'external_id')
    # ### end Alembic commands ###
