"""adding key mask and client_id

Revision ID: 7aa825c4db9f
Revises: 9cc4cbf4cab0
Create Date: 2026-03-13 17:40:40.900639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa825c4db9f'
down_revision: Union[str, Sequence[str], None] = '9cc4cbf4cab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('api_keys', sa.Column('key_mask', sa.String(), nullable=False))
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_client_id'), 'api_keys', ['client_id'], unique=False)
    op.drop_constraint(op.f('api_keys_user_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('api_keys', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_user_id_fkey'), 'api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_api_keys_client_id'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('api_keys', 'key_mask')
    op.drop_column('api_keys', 'client_id')
    # ### end Alembic commands ###
