"""add auto generation of payment exernal ids

Revision ID: 9803670ae6f8
Revises: dd52b6251899
Create Date: 2026-07-30 20:53:20.888049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9803670ae6f8'
down_revision: Union[str, Sequence[str], None] = 'dd52b6251899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
