"""adding addtional field to user model

Revision ID: a89511f9daf0
Revises: d8b772702f74
Create Date: 2026-08-06 14:04:07.459378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89511f9daf0'
down_revision: Union[str, Sequence[str], None] = 'd8b772702f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_currency', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'default_currency')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'external_id')
    # ### end Alembic commands ###
