"""adding fields billing_frequency and next_billing_date to projects model

Revision ID: b258a0bf3d4f
Revises: 9f6ed504d9a3
Create Date: 2026-08-04 12:14:42.324359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b258a0bf3d4f'
down_revision: Union[str, Sequence[str], None] = '9f6ed504d9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('billing_frequency', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'next_billing_date')
    op.drop_column('projects', 'billing_frequency')
    # ### end Alembic commands ###
