"""making external_id for pricing and event_type not nullable

Revision ID: b92bf6f31820
Revises: 49293e5ad4f9
Create Date: 2026-08-21 09:49:29.660356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92bf6f31820'
down_revision: Union[str, Sequence[str], None] = '49293e5ad4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_types', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pricing_rules', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pricing_rules', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event_types', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
