"""adding unique constrait to EventType model with project_id and event_code

Revision ID: c793e84e4753
Revises: f1fe3c4526ef
Create Date: 2026-07-22 16:49:53.122923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c793e84e4753'
down_revision: Union[str, Sequence[str], None] = 'f1fe3c4526ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_event_code', 'event_types', ['project_id', 'event_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_event_code', 'event_types', type_='unique')
    # ### end Alembic commands ###
