"""added invoice_id to usageEvent model

Revision ID: d7b9bb6e23a7
Revises: 468736bc89f7
Create Date: 2026-05-28 16:26:55.662534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b9bb6e23a7'
down_revision: Union[str, Sequence[str], None] = '468736bc89f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_events', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usage_events', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_events', type_='foreignkey')
    op.drop_column('usage_events', 'invoice_id')
    # ### end Alembic commands ###
