"""making billing frequency field in projects not nullabe

Revision ID: d8b772702f74
Revises: b258a0bf3d4f
Create Date: 2026-08-04 12:19:34.036133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b772702f74'
down_revision: Union[str, Sequence[str], None] = 'b258a0bf3d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'billing_frequency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'billing_frequency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
