"""adding external_id to refunds

Revision ID: edae8c374282
Revises: 01e4a2c67070
Create Date: 2026-08-11 13:18:23.064754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edae8c374282'
down_revision: Union[str, Sequence[str], None] = '01e4a2c67070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('external_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'refunds', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refunds', type_='unique')
    op.drop_column('refunds', 'external_id')
    # ### end Alembic commands ###
