"""making event_type_id not nullable 

Revision ID: f1fe3c4526ef
Revises: 133c28e9ffb4
Create Date: 2026-07-21 16:49:21.786604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fe3c4526ef'
down_revision: Union[str, Sequence[str], None] = '133c28e9ffb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_items', 'event_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invoice_items', 'event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('invoice_items', 'event_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
