"""added field failure reason to capture reason when refunds fail

Revision ID: f4eb34c8f182
Revises: edae8c374282
Create Date: 2026-08-12 15:32:39.994692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4eb34c8f182'
down_revision: Union[str, Sequence[str], None] = 'edae8c374282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('failure_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refunds', 'failure_reason')
    # ### end Alembic commands ###
